.catalog:
  name: "Redis Cluster"
  version: "v1.0.0"
  description: |
    Redis Sentinel Cluster
  questions:
    - variable: REDIS_VERSION
      label: "Redis version"
      type: enum
      options:
        - redis:4.0.2-alpine
        - redis:3.2.11-alpine
      default: redis:4.0.2-alpine
      required: true
    - variable: REDIS_PASSWORD
      label: "Redis auth password"
      type: password
      required: true
    - variable: REDIS_NODES
      label: Number of redis nodes
      description: Set 1 for only one master or more if add one or more slaves
      type: int
      default: 1
      required: true
    - variable: REDIS_HAPROXY_PORT
      label: "Redis port"
      type: int
      default: 6379
      required: true
    - variable: REDIS_SERVER_HOST_LABEL
      label: "Host label for redis server node"
      type: string
      required: false
    - variable: REDIS_SENTINEL_HOST_LABEL
      label: "Host label for sentinel and lb"
      type: string
      required: false
    - variable: SENTINEL_QUORUM
      label: Sentinel quorum
      description: |
        The number of Sentinel processes that need to detect an error condition in order for a master to be flagged as ODOWN
      type: int
      default: 2
      required: true
    - variable: SENTINEL_DOWN_AFTER
      label: Sentinel down-after-milliseconds
      description: |
        The time in milliseconds an instance should not be reachable for a Sentinel starting to think it is down.
      type: int
      default: 1000
      required: true
    - variable: SENTINEL_FAILOVER
      label: Sentinel failover-timeout
      description: The time to failover the same master again.
      type: int
      default: 1000
      required: true
    - variable: REDIS_VOLUME_NAME
      label: Volume Name of server nodes (Optional)
      description: |
        To store the redis data.
        By default this will be a (host scoped) named Docker volume. See "Persistent Storage Driver" for other options.
      type: string
      required: false
    - variable: SENTINEL_VOLUME_NAME
      label: Volume Name of sentinel nodes (Optional)
      description: |
        To store the sentinel data.
        By default this will be a (host scoped) named Docker volume. See "Persistent Storage Driver" for other options.
      type: string
      required: false
    - variable: STORAGE_DRIVER
      label: Volume Storage Driver (Optional)
      description: |
        To use a stack scoped volume backed by a persistent storage service, select the name
        of an existing storage driver (see `Infrastructure -> Storage`). This also requires "Volume Name" to be set.
      type: enum
      options:
        - local
        - rancher-nfs
      required: false

version: '2'
services:
  redis-sentinel:
    scale: 1
    start_on_create: true
  haproxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        backend redis-server
          option tcplog
          option tcp-check
          tcp-check send AUTH\ ${REDIS_PASSWORD}\r\n
          tcp-check expect string +OK
          tcp-check send PING\r\n
          tcp-check expect string +PONG
          tcp-check send info\ replication\r\n
          tcp-check expect string role:master
          tcp-check send QUIT\r\n
          tcp-check expect string +OK
      port_rules:
      - priority: 1
        protocol: tcp
        service: redis-server
        source_port: ${REDIS_HAPROXY_PORT}
        target_port: 6379
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  redis-server:
    scale: ${REDIS_NODES}
    retain_ip: true
